<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <Version>1.0.2025.0510</Version>
    <AssemblyVersion>1.0.2025.0510</AssemblyVersion>
    <FileVersion>1.0.2025.0510</FileVersion>
  </PropertyGroup>
</Project>
